SRC =	CommandCD.cpp \
	CommandCP.cpp \
	CommandDIR.cpp \
	CommandEXIT.cpp \
	CommandFDISK.cpp \
	CommandParser.cpp \
	FileSystemTree.cpp \
	Node.cpp \
	NodeInformation.cpp \
	ParseLinkCD.cpp \
	ParseLinkCP.cpp \
	ParseLinkDIR.cpp \
	ParseLinkEXIT.cpp \
	ParseLinkFDISK.cpp \
	UDF.cpp \
	main.cpp \
	Prompt.cpp
all:
	g++ $(SRC) -ggdb3 -o test
